import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import {
  ArrowRight, Upload, Play, Brain,
  CheckCircle, ChevronDown, Zap,
  TrendingUp, MoveRight, CircleCheck,
  Sparkles, Star, Sun, Moon
} from 'lucide-react';
import { useTheme } from '../context/ThemeContext';
import { useAuth } from '../context/AuthContext';

/* ─── scroll hook ─── */
const useScrolled = () => {
  const [scrolled, setScrolled] = useState(false);
  useEffect(() => {
    const fn = () => setScrolled(window.scrollY > 20);
    window.addEventListener('scroll', fn);
    return () => window.removeEventListener('scroll', fn);
  }, []);
  return scrolled;
};

/* ─── FAQ data ─── */
const faqs = [
  { q: 'How does the AI interview work?', a: 'Our AI conducts real-time voice and text interviews, adapts questions based on your answers, and gives instant feedback on content, clarity, and confidence.' },
  { q: 'Can I practice for specific companies?', a: 'Yes. We have curated question banks for 500+ companies including FAANG, startups, and product companies — filtered by role and recency.' },
  { q: 'How is feedback generated?', a: 'Feedback is generated by a fine-tuned LLM that evaluates your answer against ideal responses, scoring communication, technical depth, and structure.' },
  { q: 'Is my resume data secure?', a: 'Absolutely. Your resume is processed in-memory for question generation and never stored or shared with third parties.' },
  { q: 'Can I track my progress over time?', a: 'Yes. Your dashboard shows session history, score trends, weak areas, and improvement velocity across all practice types.' },
];

/* ─── testimonials ─── */
const testimonials = [
  { name: 'Arjun Mehta', role: 'SDE', text: 'PlaceMate AI helped me crack my L4 interview. The feedback was brutally honest and exactly what I needed.', stars: 5 },
  { name: 'Priya Sharma', role: 'Product SDE', text: 'The company-specific questions are incredibly accurate. I got asked 3 of the exact same questions in my actual interview.', stars: 5 },
  { name: 'Rahul Verma', role: 'Backend Developer', text: 'I went from bombing every mock to clearing 4 rounds in a row. The progress tracking kept me accountable.', stars: 5 },
  { name: 'Sneha Iyer', role: 'ML Engineer', text: 'The AI feedback on my communication style was a game changer. No human coach gave me this level of detail.', stars: 5 },
];

/* ─── features ─── */
const features = [
  { title: 'Resume-Tailored Questions', desc: 'Upload your CV and get questions crafted specifically for your experience, skills, and target role.', gradient: 'from-violet-500 to-indigo-500', tag: 'Personalized', link: '/dashboard' },
  { title: 'Real-Time AI Feedback', desc: 'Get scored on technical depth, communication clarity, and answer structure — instantly after every response.', gradient: 'from-blue-500 to-cyan-500', tag: 'Instant', link: '/dashboard' },
  { title: 'Company Question Banks', desc: '500+ companies. Filtered by recency, role, and difficulty. Practice exactly what gets asked.', gradient: 'from-emerald-500 to-teal-500', tag: '500+ Companies', link: '/dashboard' },
  { title: 'Live Coding Practice', desc: 'Solve DSA problems in an in-browser IDE with AI hints, complexity analysis, and optimal solutions.', gradient: 'from-orange-500 to-rose-500', tag: 'DSA + System Design', link: '/dashboard' },
  { title: 'Progress Analytics', desc: 'Track score trends, identify weak areas, and measure improvement velocity across every session.', gradient: 'from-purple-500 to-pink-500', tag: 'Data-Driven', link: '/dashboard' },
  { title: 'Face-to-Face Simulation', desc: 'Camera-on mock interviews with AI that reads your tone, pacing, and confidence in real time.', gradient: 'from-indigo-500 to-violet-500', tag: 'Behavioral', link: '/dashboard' },
];

/* ─── steps ─── */
const steps = [
  { num: '01', title: 'Upload Your Resume', desc: 'Drop your CV and let the AI parse your experience, skills, and target role.' },
  { num: '02', title: 'Choose Interview Type', desc: 'Pick from General, Technical, Behavioral, Coding, or Company-Specific sessions.' },
  { num: '03', title: 'Practice with AI', desc: 'Answer questions in real time. The AI adapts difficulty based on your responses.' },
  { num: '04', title: 'Get Detailed Feedback', desc: 'Receive a scored report with strengths, gaps, and a personalized improvement plan.' },
];

/* ─── theme-aware FAQ item ─── */
const FAQItem = ({ q, a, dark }) => {
  const [open, setOpen] = useState(false);
  return (
    <div
      onClick={() => setOpen(!open)}
      className={`border rounded-xl overflow-hidden transition-all duration-300 cursor-pointer ${
        dark
          ? open ? 'border-indigo-500/40 bg-indigo-950/30' : 'border-white/10 bg-white/5 hover:border-white/20'
          : open ? 'border-indigo-400/40 bg-indigo-50' : 'border-slate-200 bg-white hover:border-indigo-300 shadow-sm'
      }`}
    >
      <div className="flex items-center justify-between px-6 py-5">
        <span className={`font-medium text-sm sm:text-base ${dark ? 'text-white' : 'text-slate-800'}`}>{q}</span>
        <ChevronDown className={`w-5 h-5 flex-shrink-0 ml-4 transition-transform duration-300 ${open ? 'rotate-180' : ''} ${dark ? 'text-indigo-400' : 'text-indigo-500'}`} />
      </div>
      {open && (
        <div className={`px-6 pb-5 text-sm leading-relaxed border-t pt-4 ${dark ? 'text-slate-400 border-white/10' : 'text-slate-500 border-slate-100'}`}>
          {a}
        </div>
      )}
    </div>
  );
};

/* ══════════════════════════════════════════════
   MAIN COMPONENT
══════════════════════════════════════════════ */
const Landing = () => {
  const scrolled = useScrolled();
  const { dark, toggleTheme } = useTheme();
  const { user } = useAuth();

  /* shorthand theme tokens */
  const t = {
    bg:           dark ? 'bg-[#080B14]'          : 'bg-white',
    text:         dark ? 'text-white'             : 'text-slate-900',
    subtext:      dark ? 'text-slate-400'         : 'text-slate-500',
    border:       dark ? 'border-white/10'        : 'border-slate-200',
    cardBg:       dark ? 'bg-white/[0.03]'        : 'bg-white',
    cardHover:    dark ? 'hover:bg-white/[0.06] hover:border-white/20' : 'hover:border-indigo-300 hover:shadow-lg',
    sectionBorder:dark ? 'border-white/10'        : 'border-slate-100',
    mutedLabel:   dark ? 'text-slate-500'         : 'text-slate-400',
    navBg:        dark
                    ? scrolled ? 'bg-[#080B14]/80 backdrop-blur-xl border-b border-white/10 shadow-xl shadow-black/20' : 'bg-transparent'
                    : scrolled ? 'bg-white/90 backdrop-blur-xl border-b border-slate-200 shadow-sm' : 'bg-transparent',
    navLink:      dark ? 'text-slate-400 hover:text-white' : 'text-slate-500 hover:text-slate-900',
    navSignIn:    dark ? 'text-slate-400 hover:text-white' : 'text-slate-600 hover:text-slate-900',
    statsBg:      dark ? 'bg-white/[0.02] border-white/10' : 'bg-slate-50 border-slate-100',
    mockupBg:     dark ? 'bg-[#0D1117] border-white/10'   : 'bg-slate-50 border-slate-200',
    mockupBar:    dark ? 'bg-white/5 border-white/10'      : 'bg-slate-100 border-slate-200',
    mockupMsg:    dark ? 'bg-white/5 border-white/10 text-slate-300' : 'bg-white border-slate-200 text-slate-700',
    mockupReply:  dark ? 'bg-indigo-600/20 border-indigo-500/30 text-slate-200' : 'bg-indigo-50 border-indigo-200 text-indigo-900',
    mockupUser:   dark ? 'bg-slate-700' : 'bg-indigo-100 text-indigo-700',
    floatCard:    dark ? 'bg-[#0F1629]/90 border-white/10' : 'bg-white border-slate-200 shadow-xl',
    floatText:    dark ? 'text-slate-400' : 'text-slate-500',
    floatVal:     dark ? 'text-white' : 'text-slate-900',
    analyticsBg:  dark ? 'bg-[#0D1117] border-white/10'   : 'bg-white border-slate-200 shadow-lg',
    metricBg:     dark ? 'bg-white/5 border-white/10'     : 'bg-slate-50 border-slate-200',
    stepBg:       dark ? 'bg-white/[0.03] border-white/10 hover:border-indigo-500/30' : 'bg-white border-slate-200 hover:border-indigo-400 shadow-sm hover:shadow-md',
    stepNum:      dark ? 'text-white/5' : 'text-slate-100',
    stepBadge:    dark ? 'bg-indigo-600/20 border-indigo-500/30 text-indigo-400' : 'bg-indigo-50 border-indigo-200 text-indigo-600',
    testiBg:      dark ? 'bg-white/[0.03] border-white/10 hover:border-white/20' : 'bg-white border-slate-200 hover:border-indigo-300 shadow-sm hover:shadow-md',
    testiText:    dark ? 'text-slate-300' : 'text-slate-600',
    techText:     dark ? 'text-slate-300' : 'text-slate-400',
    techLabel:    dark ? 'text-slate-600' : 'text-slate-400',
    ctaBg:        dark ? 'bg-gradient-to-br from-indigo-950/80 to-violet-950/80 border-indigo-500/20' : 'bg-gradient-to-br from-indigo-600 to-violet-600 border-transparent',
    ctaText:      dark ? 'text-white' : 'text-white',
    ctaSub:       dark ? 'text-slate-400' : 'text-indigo-100',
    ctaSecBtn:    dark ? 'bg-white/5 hover:bg-white/10 border-white/15 text-white' : 'bg-white/20 hover:bg-white/30 border-white/30 text-white',
    footerBg:     dark ? '' : 'bg-slate-50',
    footerText:   dark ? 'text-slate-500' : 'text-slate-500',
    footerLink:   dark ? 'hover:text-indigo-400' : 'hover:text-indigo-600',
    footerDivider:dark ? 'border-white/10' : 'border-slate-200',
    footerCopy:   dark ? 'text-slate-600' : 'text-slate-400',
    badgeBg:      dark ? 'border-indigo-500/30 bg-indigo-500/10 text-indigo-300' : 'border-indigo-200 bg-indigo-50 text-indigo-600',
    tagBorder:    dark ? 'border-white/10 text-slate-500' : 'border-slate-200 text-slate-400 bg-slate-50',
    checklistText:dark ? 'text-slate-300' : 'text-slate-700',
  };

  return (
    <div className={`min-h-screen ${t.bg} ${t.text} overflow-x-hidden transition-colors duration-300`}>

      {/* ── ambient glow blobs (dark only) ── */}
      {dark && (
        <div className="fixed inset-0 pointer-events-none overflow-hidden z-0">
          <div className="absolute -top-40 -left-40 w-[600px] h-[600px] bg-indigo-600/20 rounded-full blur-[120px]" />
          <div className="absolute top-1/3 -right-40 w-[500px] h-[500px] bg-violet-600/15 rounded-full blur-[120px]" />
          <div className="absolute bottom-0 left-1/3 w-[400px] h-[400px] bg-blue-600/10 rounded-full blur-[100px]" />
        </div>
      )}
      {/* light: subtle top gradient */}
      {!dark && (
        <div className="fixed inset-0 pointer-events-none overflow-hidden z-0">
          <div className="absolute -top-20 left-0 right-0 h-[500px] bg-gradient-to-b from-indigo-50/80 to-transparent" />
        </div>
      )}

      {/* ════════ NAVBAR ════════ */}
      <nav className={`fixed top-0 left-0 right-0 z-50 transition-all duration-300 ${t.navBg}`}>
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link to={user ? "/dashboard" : "/"} className="flex items-center gap-3">
            <img src="/MY_LOGO.png" alt="PlaceMate AI" className="w-9 h-9 object-contain" />
            <span className="text-lg font-bold tracking-tight">PlaceMate AI</span>
          </Link>
          <div className={`hidden md:flex items-center gap-8 text-sm ${t.navLink}`}>
            <a href="#features" className="transition-colors">Features</a>
            <a href="#how-it-works" className="transition-colors">How it works</a>
            <a href="#testimonials" className="transition-colors">Reviews</a>
            <a href="#faq" className="transition-colors">FAQ</a>
          </div>
          <div className="flex items-center gap-3">
            {/* theme toggle */}
            <button
              onClick={() => toggleTheme()}
              className={`w-9 h-9 rounded-lg flex items-center justify-center transition-all duration-200 ${
                dark ? 'bg-white/10 hover:bg-white/15 text-slate-300' : 'bg-slate-100 hover:bg-slate-200 text-slate-600'
              }`}
              aria-label="Toggle theme"
            >
              {dark ? <Sun className="w-4 h-4" /> : <Moon className="w-4 h-4" />}
            </button>
            {user ? (
              <Link to="/dashboard" className="flex items-center gap-2 text-sm font-semibold bg-indigo-600 hover:bg-indigo-500 text-white px-5 py-2.5 rounded-lg transition-all duration-200 hover:shadow-lg hover:shadow-indigo-500/25">
                Go to Dashboard <ArrowRight className="w-4 h-4" />
              </Link>
            ) : (
              <>
                <Link to="/sign-in" className={`text-sm px-4 py-2 transition-colors ${t.navSignIn}`}>Sign In</Link>
                <Link to="/sign-in" className="flex items-center gap-2 text-sm font-semibold bg-indigo-600 hover:bg-indigo-500 text-white px-5 py-2.5 rounded-lg transition-all duration-200 hover:shadow-lg hover:shadow-indigo-500/25">
                  Get Started <ArrowRight className="w-4 h-4" />
                </Link>
              </>
            )}
          </div>
        </div>
      </nav>

      {/* ════════ HERO ════════ */}
      <section className="relative z-10 pt-36 pb-24 px-6">
        <div className="max-w-7xl mx-auto">
          <div className="flex justify-start mb-8">
            <div className={`inline-flex items-center gap-2 px-4 py-2 rounded-full border text-sm font-medium ${t.badgeBg}`}>
              <Sparkles className="w-4 h-4" />
              AI-Powered Mock Interviews — Now Live
            </div>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">
            <div>
              <h1 className="text-5xl sm:text-6xl font-bold leading-[1.1] tracking-tight mb-6">
                Land your dream job with{' '}
                <span className="bg-gradient-to-r from-indigo-500 via-violet-500 to-blue-500 bg-clip-text text-transparent">
                  AI-driven
                </span>{' '}
                interview prep
              </h1>
              <p className={`text-lg leading-relaxed mb-10 max-w-lg ${t.subtext}`}>
                Practice real interview questions, get instant AI feedback, and track your improvement — all tailored to your resume and target company.
              </p>
              <div className="flex flex-wrap gap-4 mb-10">
                <Link to={user ? "/dashboard" : "/sign-in"} className="flex items-center gap-2 px-7 py-3.5 bg-indigo-600 hover:bg-indigo-500 text-white font-semibold rounded-xl transition-all duration-200 hover:shadow-xl hover:shadow-indigo-500/30 hover:-translate-y-0.5">
                  <Play className="w-4 h-4" /> {user ? 'Go to Dashboard' : 'Start Practicing Free'}
                </Link>
                <Link to={user ? "/cv-upload" : "/sign-in"} className={`flex items-center gap-2 px-7 py-3.5 font-semibold rounded-xl border transition-all duration-200 ${
                  dark ? 'bg-white/5 hover:bg-white/10 border-white/15 text-white' : 'bg-white hover:bg-slate-50 border-slate-300 text-slate-700 shadow-sm'
                }`}>
                  <Upload className="w-4 h-4" /> Upload Resume
                </Link>
              </div>
              <div className={`flex flex-wrap items-center gap-6 text-sm ${t.subtext}`}>
                <span className="flex items-center gap-1.5"><CircleCheck className="w-4 h-4 text-emerald-500" /> No credit card</span>
                <span className="flex items-center gap-1.5"><CircleCheck className="w-4 h-4 text-emerald-500" /> Free to start</span>
                <span className="flex items-center gap-1.5"><CircleCheck className="w-4 h-4 text-emerald-500" /> 500+ companies</span>
              </div>
            </div>

            {/* mockup */}
            <div className="relative">
              <div className={`absolute -top-6 -left-6 z-20 backdrop-blur-sm border rounded-2xl px-5 py-4 ${t.floatCard}`}>
                <div className={`text-xs mb-1 ${t.floatText}`}>Interview Score</div>
                <div className={`text-2xl font-bold ${t.floatVal}`}>87<span className="text-indigo-500">/100</span></div>
                <div className="flex items-center gap-1 text-emerald-500 text-xs mt-1"><TrendingUp className="w-3 h-3" /> +12 this week</div>
              </div>
              <div className={`absolute -bottom-4 -right-4 z-20 backdrop-blur-sm border rounded-2xl px-5 py-4 ${t.floatCard}`}>
                <div className={`text-xs mb-1 ${t.floatText}`}>Sessions Done</div>
                <div className={`text-2xl font-bold ${t.floatVal}`}>24</div>
                <div className="flex items-center gap-1 text-indigo-500 text-xs mt-1"><Zap className="w-3 h-3" /> 3 today</div>
              </div>
              <div className={`relative border rounded-2xl overflow-hidden shadow-2xl ${t.mockupBg} ${dark ? 'shadow-black/50' : 'shadow-slate-200'}`}>
                <div className={`flex items-center gap-2 px-4 py-3 border-b ${t.mockupBar}`}>
                  <div className="w-3 h-3 rounded-full bg-rose-400/70" />
                  <div className="w-3 h-3 rounded-full bg-amber-400/70" />
                  <div className="w-3 h-3 rounded-full bg-emerald-400/70" />
                  <span className={`ml-3 text-xs ${t.subtext}`}>PlaceMate AI — Interview Session</span>
                </div>
                <div className="p-6 space-y-4">
                  <div className="flex items-start gap-3">
                    <div className="w-8 h-8 rounded-full bg-indigo-600 flex items-center justify-center flex-shrink-0">
                      <Brain className="w-4 h-4 text-white" />
                    </div>
                    <div className={`border rounded-xl rounded-tl-none px-4 py-3 text-sm max-w-xs ${t.mockupMsg}`}>
                      Tell me about a time you optimized a slow database query. Walk me through your approach.
                    </div>
                  </div>
                  <div className="flex items-start gap-3 justify-end">
                    <div className={`border rounded-xl rounded-tr-none px-4 py-3 text-sm max-w-xs ${t.mockupReply}`}>
                      I identified an N+1 query issue using query profiling, then added eager loading and a composite index...
                    </div>
                    <div className={`w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 text-xs font-bold ${t.mockupUser}`}>U</div>
                  </div>
                  <div className={`rounded-xl px-4 py-3 ${dark ? 'bg-emerald-500/10 border border-emerald-500/20' : 'bg-emerald-50 border border-emerald-200'}`}>
                    <div className="flex items-center gap-2 text-emerald-600 text-xs font-semibold mb-2">
                      <CheckCircle className="w-3.5 h-3.5" /> AI Feedback
                    </div>
                    <div className="space-y-1.5">
                      {[['Technical Depth', 90], ['Communication', 82], ['Structure', 88]].map(([label, val]) => (
                        <div key={label} className="flex items-center gap-3">
                          <span className={`text-xs w-28 ${t.subtext}`}>{label}</span>
                          <div className={`flex-1 h-1.5 rounded-full overflow-hidden ${dark ? 'bg-white/10' : 'bg-slate-200'}`}>
                            <div className="h-full bg-gradient-to-r from-emerald-500 to-teal-400 rounded-full" style={{ width: `${val}%` }} />
                          </div>
                          <span className={`text-xs w-6 ${t.subtext}`}>{val}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ════════ STATS STRIP ════════ */}
      <section className={`relative z-10 border-y py-10 px-6 ${t.statsBg}`}>
        <div className="max-w-5xl mx-auto grid grid-cols-2 md:grid-cols-4 gap-8 text-center">
          {[
            { val: '10K+', label: 'Practice Sessions', color: 'text-indigo-500' },
            { val: '95%',  label: 'Placement Rate',    color: 'text-emerald-500' },
            { val: '500+', label: 'Companies Covered', color: 'text-violet-500' },
            { val: '24/7', label: 'AI Availability',   color: 'text-blue-500' },
          ].map(({ val, label, color }) => (
            <div key={label}>
              <div className={`text-4xl font-bold ${color} mb-1`}>{val}</div>
              <div className={`text-sm ${t.mutedLabel}`}>{label}</div>
            </div>
          ))}
        </div>
      </section>

      {/* ════════ FEATURES ════════ */}
      <section id="features" className="relative z-10 py-28 px-6">
        <div className="max-w-7xl mx-auto">
          <div className="mb-4"><span className="text-indigo-500 text-sm font-semibold uppercase tracking-widest">Features</span></div>
          <div className="flex flex-col md:flex-row md:items-end md:justify-between gap-6 mb-16">
            <h2 className="text-4xl sm:text-5xl font-bold leading-tight max-w-xl">
              Everything you need to{' '}
              <span className="bg-gradient-to-r from-indigo-500 to-violet-500 bg-clip-text text-transparent">ace the interview</span>
            </h2>
            <p className={`max-w-sm text-sm leading-relaxed ${t.subtext}`}>
              From resume parsing to live coding — one platform covers your entire interview preparation journey.
            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
            {features.map(({ title, desc, gradient, tag, link }, i) => (
              <Link
                to={link}
                key={title}
                className={`group relative border rounded-2xl p-6 transition-all duration-300 hover:-translate-y-1 cursor-pointer
                  ${t.cardBg} ${t.border} ${t.cardHover}
                  ${dark ? 'hover:shadow-2xl hover:shadow-black/30' : 'shadow-sm'}
                  ${i === 0 ? 'md:col-span-2 lg:col-span-1' : ''}`}
              >
                <div className={`absolute inset-0 rounded-2xl bg-gradient-to-br ${gradient} opacity-0 group-hover:opacity-5 transition-opacity duration-300`} />
                <div className="relative z-10">
                  <div className="flex items-start justify-between mb-5">
                    <span className={`text-xs font-medium border rounded-full px-3 py-1 ${t.tagBorder}`}>{tag}</span>
                  </div>
                  <h3 className={`font-semibold text-lg mb-2 ${t.text}`}>{title}</h3>
                  <p className={`text-sm leading-relaxed ${t.subtext}`}>{desc}</p>
                  <div className="mt-5 flex items-center gap-1 text-indigo-500 text-sm font-medium opacity-0 group-hover:opacity-100 transition-opacity duration-200">
                    Get started <MoveRight className="w-4 h-4" />
                  </div>
                </div>
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* ════════ HOW IT WORKS ════════ */}
      <section id="how-it-works" className={`relative z-10 py-28 px-6 border-t ${t.sectionBorder}`}>
        <div className="max-w-7xl mx-auto">
          <div className="mb-4"><span className="text-violet-500 text-sm font-semibold uppercase tracking-widest">Process</span></div>
          <h2 className="text-4xl sm:text-5xl font-bold mb-20 max-w-lg leading-tight">
            From zero to offer-ready in 4 steps
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {steps.map(({ num, title, desc }, i) => (
              <div key={num} className={`relative border rounded-2xl p-8 transition-all duration-300 ${t.stepBg} ${i % 2 === 1 ? 'md:mt-8' : ''}`}>
                <div className={`text-6xl font-black absolute top-6 right-8 select-none ${t.stepNum}`}>{num}</div>
                <div className="relative z-10">
                  <div className={`w-10 h-10 rounded-xl border flex items-center justify-center mb-5 ${t.stepBadge}`}>
                    <span className="font-bold text-sm">{num}</span>
                  </div>
                  <h3 className={`font-semibold text-xl mb-3 ${t.text}`}>{title}</h3>
                  <p className={`text-sm leading-relaxed ${t.subtext}`}>{desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ════════ ANALYTICS ════════ */}
      <section className={`relative z-10 py-28 px-6 border-t ${t.sectionBorder}`}>
        <div className="max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">
          <div>
            <span className="text-emerald-500 text-sm font-semibold uppercase tracking-widest">Analytics</span>
            <h2 className="text-4xl sm:text-5xl font-bold mt-4 mb-6 leading-tight">Know exactly where you stand</h2>
            <p className={`leading-relaxed mb-8 ${t.subtext}`}>
              Every session generates a detailed performance report. Track your score trends, identify weak topics, and see your improvement velocity over time.
            </p>
            <ul className="space-y-3">
              {['Session-by-session score history', 'Topic-wise strength breakdown', 'Communication & confidence scoring', 'Personalized improvement roadmap'].map(item => (
                <li key={item} className={`flex items-center gap-3 text-sm ${t.checklistText}`}>
                  <CheckCircle className="w-4 h-4 text-emerald-500 flex-shrink-0" />{item}
                </li>
              ))}
            </ul>
          </div>
          <div className={`border rounded-2xl p-6 ${t.analyticsBg}`}>
            <div className="flex items-center justify-between mb-6">
              <span className={`font-semibold ${t.text}`}>Performance Overview</span>
              <span className={`text-xs border rounded-full px-3 py-1 ${t.subtext} ${t.border}`}>Last 30 days</span>
            </div>
            <div className="flex items-end gap-2 h-32 mb-6">
              {[55, 62, 58, 70, 74, 68, 80, 77, 85, 87].map((h, i) => (
                <div key={i} className="flex-1 rounded-t-md bg-gradient-to-t from-indigo-600 to-violet-500 opacity-80 hover:opacity-100 transition-opacity" style={{ height: `${h}%` }} />
              ))}
            </div>
            <div className="grid grid-cols-3 gap-3">
              {[
                { label: 'Avg Score', val: '82', color: 'text-indigo-500' },
                { label: 'Sessions',  val: '24', color: 'text-violet-500' },
                { label: 'Streak',    val: '7d', color: 'text-emerald-500' },
              ].map(({ label, val, color }) => (
                <div key={label} className={`border rounded-xl p-3 text-center ${t.metricBg} ${t.border}`}>
                  <div className={`text-xl font-bold ${color}`}>{val}</div>
                  <div className={`text-xs mt-0.5 ${t.subtext}`}>{label}</div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ════════ TESTIMONIALS ════════ */}
      <section id="testimonials" className={`relative z-10 py-28 px-6 border-t ${t.sectionBorder}`}>
        <div className="max-w-7xl mx-auto">
          <div className="mb-4"><span className="text-blue-500 text-sm font-semibold uppercase tracking-widest">Reviews</span></div>
          <div className="flex flex-col md:flex-row md:items-end md:justify-between gap-6 mb-14">
            <h2 className="text-4xl sm:text-5xl font-bold leading-tight max-w-md">Trusted by students who got the job</h2>
            <div className={`flex items-center gap-2 text-sm ${t.subtext}`}>
              <div className="flex">{[...Array(5)].map((_, i) => <Star key={i} className="w-4 h-4 text-amber-400 fill-amber-400" />)}</div>
              4.9 / 5 from 2,000+ reviews
            </div>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
            {testimonials.map(({ name, role, text, stars }, i) => (
              <div key={name} className={`border rounded-2xl p-7 transition-all duration-300 ${t.testiBg} ${i === 1 ? 'md:mt-6' : ''} ${i === 3 ? 'md:-mt-6' : ''}`}>
                <div className="flex mb-4">{[...Array(stars)].map((_, j) => <Star key={j} className="w-4 h-4 text-amber-400 fill-amber-400" />)}</div>
                <p className={`text-sm leading-relaxed mb-6 ${t.testiText}`}>"{text}"</p>
                <div className="flex items-center gap-3">
                  <div className="w-9 h-9 rounded-full bg-gradient-to-br from-indigo-500 to-violet-500 flex items-center justify-center text-white text-sm font-bold">{name[0]}</div>
                  <div>
                    <div className={`text-sm font-semibold ${t.text}`}>{name}</div>
                    <div className={`text-xs ${t.subtext}`}>{role}</div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ════════ TECH STRIP ════════ */}
      <section className={`relative z-10 py-16 px-6 border-t ${t.sectionBorder}`}>
        <div className="max-w-5xl mx-auto text-center">
          <p className={`text-sm uppercase tracking-widest mb-8 ${t.techLabel}`}>Powered by</p>
          <div className="flex flex-wrap justify-center items-center gap-8 opacity-40">
            {['React', 'Node.js', 'MongoDB', 'OpenAI', 'Tailwind CSS', 'Vite'].map(tech => (
              <span key={tech} className={`font-semibold text-sm ${t.techText}`}>{tech}</span>
            ))}
          </div>
        </div>
      </section>

      {/* ════════ FAQ ════════ */}
      <section id="faq" className={`relative z-10 py-28 px-6 border-t ${t.sectionBorder}`}>
        <div className="max-w-3xl mx-auto">
          <div className="mb-4 text-center"><span className="text-violet-500 text-sm font-semibold uppercase tracking-widest">FAQ</span></div>
          <h2 className="text-4xl font-bold text-center mb-14">Common questions</h2>
          <div className="space-y-3">
            {faqs.map(faq => <FAQItem key={faq.q} {...faq} dark={dark} />)}
          </div>
        </div>
      </section>

      {/* ════════ CTA ════════ */}
      <section className="relative z-10 py-28 px-6">
        <div className="max-w-4xl mx-auto relative">
          {dark && <div className="absolute inset-0 bg-gradient-to-r from-indigo-600/20 via-violet-600/20 to-blue-600/20 rounded-3xl blur-2xl" />}
          <div className={`relative border rounded-3xl p-14 text-center backdrop-blur-sm ${t.ctaBg}`}>
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full border border-white/20 bg-white/10 text-white text-sm font-medium mb-6">
              <Zap className="w-4 h-4" /> Start for free — no credit card needed
            </div>
            <h2 className="text-4xl sm:text-5xl font-bold mb-5 leading-tight text-white">
              Your next interview is closer than you think
            </h2>
            <p className={`mb-10 max-w-lg mx-auto ${t.ctaSub}`}>
              Join thousands of students who used PlaceMate AI to land roles at top companies.
            </p>
            <div className="flex flex-wrap justify-center gap-4">
              <Link to="/sign-up" className="flex items-center gap-2 px-8 py-4 bg-white text-indigo-600 font-semibold rounded-xl transition-all duration-200 hover:shadow-xl hover:-translate-y-0.5">
                Get Started Free <ArrowRight className="w-4 h-4" />
              </Link>
              <Link to="/sign-in" className={`flex items-center gap-2 px-8 py-4 border font-semibold rounded-xl transition-all duration-200 ${t.ctaSecBtn}`}>
                Sign In
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* ════════ FOOTER ════════ */}
      <footer className={`relative z-10 border-t py-16 px-6 ${t.sectionBorder} ${t.footerBg}`}>
        <div className="max-w-7xl mx-auto">
          <div className="grid grid-cols-1 md:grid-cols-5 gap-10 mb-14">
            <div className="md:col-span-2">
              <Link to={user ? "/dashboard" : "/"} className="flex items-center gap-3 mb-4">
                <img src="/MY_LOGO.png" alt="PlaceMate AI" className="w-9 h-9 object-contain" />
                <span className="text-lg font-bold">PlaceMate AI</span>
              </Link>
              <p className={`text-sm leading-relaxed max-w-xs ${t.footerText}`}>
                AI-powered interview preparation platform helping students land roles at top companies worldwide.
              </p>
              <div className="flex gap-4 mt-6">
                <a href="#" className={`transition-colors ${t.footerText} ${t.footerLink}`}>
                  <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24"><path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/></svg>
                </a>
                <a href="#" className={`transition-colors ${t.footerText} ${t.footerLink}`}>
                  <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg>
                </a>
                <a href="#" className={`transition-colors ${t.footerText} ${t.footerLink}`}>
                  <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24"><path d="M23.953 4.57a10 10 0 01-2.825.775 4.958 4.958 0 002.163-2.723c-.951.555-2.005.959-3.127 1.184a4.92 4.92 0 00-8.384 4.482C7.69 8.095 4.067 6.13 1.64 3.162a4.822 4.822 0 00-.666 2.475c0 1.71.87 3.213 2.188 4.096a4.904 4.904 0 01-2.228-.616v.06a4.923 4.923 0 003.946 4.827 4.996 4.996 0 01-2.212.085 4.936 4.936 0 004.604 3.417 9.867 9.867 0 01-6.102 2.105c-.39 0-.779-.023-1.17-.067a13.995 13.995 0 007.557 2.209c9.053 0 13.998-7.496 13.998-13.985 0-.21 0-.42-.015-.63A9.935 9.935 0 0024 4.59z"/></svg>
                </a>
              </div>
            </div>
            <div>
              <h4 className={`text-sm font-semibold mb-4 ${t.text}`}>Product</h4>
              <ul className={`space-y-2.5 text-sm ${t.footerText}`}>
                <li><Link to="/dashboard" className={t.footerLink}>Practice Sessions</Link></li>
                <li><Link to="/coding-practice" className={t.footerLink}>Coding Practice</Link></li>
                <li><Link to="/company-questions" className={t.footerLink}>Company Prep</Link></li>
                <li><Link to="/cv-upload" className={t.footerLink}>Resume Analyzer</Link></li>
              </ul>
            </div>
            <div>
              <h4 className={`text-sm font-semibold mb-4 ${t.text}`}>Resources</h4>
              <ul className={`space-y-2.5 text-sm ${t.footerText}`}>
                <li><a href="#" className={t.footerLink}>DSA Guide</a></li>
                <li><a href="#" className={t.footerLink}>Resume Tips</a></li>
                <li><a href="#" className={t.footerLink}>Blog</a></li>
                <li><a href="#" className={t.footerLink}>Help Center</a></li>
              </ul>
            </div>
            <div>
              <h4 className={`text-sm font-semibold mb-4 ${t.text}`}>Company</h4>
              <ul className={`space-y-2.5 text-sm ${t.footerText}`}>
                <li><a href="#" className={t.footerLink}>About</a></li>
                <li><a href="#" className={t.footerLink}>Privacy Policy</a></li>
                <li><a href="#" className={t.footerLink}>Terms of Service</a></li>
                <li><a href="#" className={t.footerLink}>Contact</a></li>
              </ul>
            </div>
          </div>
          <div className={`border-t pt-8 flex flex-col md:flex-row justify-between items-center gap-4 ${t.footerDivider}`}>
            <p className={`text-sm ${t.footerCopy}`}>© 2026 PlaceMate AI. All rights reserved.</p>
            <p className={`text-xs ${t.footerCopy}`}>Built for students. Powered by AI.</p>
          </div>
        </div>
      </footer>

    </div>
  );
};

export default Landing;
